name: Generate Activity Graph

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: Jhonorran
          options: theme=github-compact&hide_border=true
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish activity graph
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: activity-graph
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
